sequenceDiagram
    participant B as Browser
    participant A as API
    participant C as Language KB

    B ->> +A: GET /greet?name=James&lan=en
    A ->> +C: fetch(greeting, 'de')

    C ->> -A: 'Hallo!'
    A ->> -B: 'Hallo James!'
    
